# Site settings

title:      IIIF Crop
baseurl:    /doneill/iiif-crop-tool
name: IIIF Crop Tool
# url:        "http://www.troymcginnis.com"
# typekit:    pfj6jja
# ga:

# Meta Tags

# Build settings
include: ['_pages']

permalink: pretty

# Plugins


markdown:    kramdown
